{id: 1, name: "A dos Cunhados"},
{id: 2, name: "A dos Francos"},
{id: 3, name: "Aboim da Nóbrega"},
{id: 4, name: "Abrantes"},
{id: 5, name: "Abraveses"},
{id: 6, name: "Abrigada"},
{id: 7, name: "Adaúfe"},
{id: 8, name: "Água de Pau"},
{id: 9, name: "Água de Pena"},
{id: 10, name: "Água Longa"},
{id: 11, name: "Água Retorta"},
{id: 12, name: "Aguada de Cima"},
{id: 13, name: "Águas Santas"},
{id: 14, name: "Aguçadoura"},
{id: 15, name: "Águeda"},
{id: 16, name: "Aguiar da Beira"},
{id: 17, name: "Albergaria-a-Velha"},
{id: 18, name: "Albufeira"},
{id: 19, name: "Alcabideche"},
{id: 20, name: "Alcácer do Sal"},
{id: 21, name: "Alcains"},
{id: 22, name: "Alcanede"},
{id: 23, name: "Alcanena"},
{id: 24, name: "Alcanhões"},
{id: 25, name: "Alcantarilha"},
{id: 26, name: "Alcobaça"},
{id: 27, name: "Alcochete"},
{id: 28, name: "Alcoentre"},
{id: 29, name: "Aldeia de Joanes"},
{id: 30, name: "Aldeia de Paio Pires"},
{id: 31, name: "Aldeia do Mato"},
{id: 32, name: "Aldeia Nova de São Bento"},
{id: 33, name: "Alenquer"},
{id: 34, name: "Alfaião"},
{id: 35, name: "Alfarelos"},
{id: 36, name: "Alfeizerão"},
{id: 37, name: "Alfena"},
{id: 38, name: "Alferrarede"},
{id: 39, name: "Alfragide"},
{id: 40, name: "Algés"},
{id: 41, name: "Algoz"},
{id: 42, name: "Algueirão"},
{id: 43, name: "Alhadas"},
{id: 44, name: "Alhandra"},
{id: 45, name: "Alhos Vedros"},
{id: 46, name: "Alijó"},
{id: 47, name: "Aljezur"},
{id: 48, name: "Aljubarrota"},
{id: 49, name: "Aljustrel"},
{id: 50, name: "Almada"},
{id: 51, name: "Almancil"},
{id: 52, name: "Almargem"},
{id: 53, name: "Almeirim"},
{id: 54, name: "Almodôvar"},
{id: 55, name: "Almograve"},
{id: 56, name: "Alpendurada"},
{id: 57, name: "Alpiarça"},
{id: 58, name: "Alter do Chão"},
{id: 59, name: "Altura"},
{id: 60, name: "Alvalade"},
{id: 61, name: "Alvito"},
{id: 62, name: "Alvor"},
{id: 63, name: "Alvorninha"},
{id: 64, name: "Amadora"},
{id: 65, name: "Amarante"},
{id: 66, name: "Amiães de Baixo"},
{id: 67, name: "Amieira"},
{id: 68, name: "Amor"},
{id: 69, name: "Amora"},
{id: 70, name: "Amorim"},
{id: 71, name: "Ançã"},
{id: 72, name: "Angra do Heroísmo"},
{id: 73, name: "Angústias"},
{id: 74, name: "Anta"},
{id: 75, name: "Apelação"},
{id: 76, name: "Apúlia e Fão"},
{id: 77, name: "Apúlia"},
{id: 78, name: "Aradas"},
{id: 79, name: "Arazede"},
{id: 80, name: "Arco da Calheta"},
{id: 81, name: "Arco de São Jorge"},
{id: 82, name: "Arcos de Valdevez"},
{id: 83, name: "Arcos"},
{id: 84, name: "Arcozelo"},
{id: 85, name: "Areosa"},
{id: 86, name: "Arez"},
{id: 87, name: "Arganil"},
{id: 88, name: "Argivai"},
{id: 89, name: "Argoncilhe"},
{id: 90, name: "Armação de Pêra"},
{id: 91, name: "Arões"},
{id: 92, name: "Arranhó"},
{id: 93, name: "Arrentela"},
{id: 94, name: "Arrifana"},
{id: 95, name: "Arrifes"},
{id: 96, name: "Arronches"},
{id: 97, name: "Arruda dos Vinhos"},
{id: 98, name: "Árvore"},
{id: 99, name: "Assafarge"},
{id: 100, name: "Atalaia"},
{id: 101, name: "Atouguia da Baleia"},
{id: 102, name: "Avanca"},
{id: 103, name: "Aveiras de Cima"},
{id: 104, name: "Aveiro"},
{id: 105, name: "Aveleda"},
{id: 106, name: "Aver-o-Mar"},
{id: 107, name: "Aves"},
{id: 108, name: "Avintes"},
{id: 109, name: "Avô"},
{id: 110, name: "Azambuja"},
{id: 111, name: "Azeitão"},
{id: 112, name: "Azenha"},
{id: 113, name: "Azenhas do Mar"},
{id: 114, name: "Azinhaga"},
{id: 115, name: "Baçal"},
{id: 116, name: "Baguim do Monte"},
{id: 117, name: "Baião"},
{id: 118, name: "Balazar"},
{id: 119, name: "Baltar"},
{id: 120, name: "Bandeiras"},
{id: 121, name: "Barão de São João"},
{id: 122, name: "Barcarena"},
{id: 123, name: "Barcelos"},
{id: 124, name: "Barco"},
{id: 125, name: "Barqueiros"},
{id: 126, name: "Barreiro"},
{id: 127, name: "Barroca Grande"},
{id: 128, name: "Barrosas"},
{id: 129, name: "Batalha"},
{id: 130, name: "Beato António"},
{id: 131, name: "Beduido"},
{id: 132, name: "Beiriz de Baixo"},
{id: 133, name: "Beja"},
{id: 134, name: "Belas"},
{id: 135, name: "Belazaima do Chão"},
{id: 136, name: "Belver"},
{id: 137, name: "Bemfica"},
{id: 138, name: "Benavente"},
{id: 139, name: "Benedita"},
{id: 140, name: "Benfica"},
{id: 141, name: "Bensafrim"},
{id: 142, name: "Beringel"},
{id: 143, name: "Biscoitos"},
{id: 144, name: "Boaventura"},
{id: 145, name: "Boavista dos Pinheiros"},
{id: 146, name: "Bobadela"},
{id: 147, name: "Boliqueime"},
{id: 148, name: "Bombarral"},
{id: 149, name: "Borba"},
{id: 150, name: "Boticas"},
{id: 151, name: "Bougado"},
{id: 152, name: "Braga"},
{id: 153, name: "Bragança"},
{id: 154, name: "Branca"},
{id: 155, name: "Britiande"},
{id: 156, name: "Brito"},
{id: 157, name: "Buarcos"},
{id: 158, name: "Bucelas"},
{id: 159, name: "Burgau"},
{id: 160, name: "Cabanas de Tavira"},
{id: 161, name: "Cabanas de Torres"},
{id: 162, name: "Cabanas de Viriato"},
{id: 163, name: "Cabeça Gorda"},
{id: 164, name: "Cabeceiras de Basto"},
{id: 165, name: "Cabo da Praia"},
{id: 166, name: "Cabouco"},
{id: 167, name: "Cacém"},
{id: 168, name: "Cacilhas"},
{id: 169, name: "Cadafais"},
{id: 170, name: "Cadaval"},
{id: 171, name: "Cais do Pico"},
{id: 172, name: "Caldas da Rainha"},
{id: 173, name: "Caldas das Taipas"},
{id: 174, name: "Caldas de Vizela"},
{id: 175, name: "Caldelas"},
{id: 176, name: "Calendário"},
{id: 177, name: "Calheta"},
{id: 178, name: "Calves"},
{id: 179, name: "Camacha"},
{id: 180, name: "Câmara de Lobos"},
{id: 181, name: "Camarate"},
{id: 182, name: "Campanário"},
{id: 183, name: "Campelos"},
{id: 184, name: "Campo de Besteiros"},
{id: 185, name: "Campo Maior"},
{id: 186, name: "Campo"},
{id: 187, name: "Canas de Senhorim"},
{id: 188, name: "Candoso"},
{id: 189, name: "Caneças"},
{id: 190, name: "Canelas"},
{id: 191, name: "Canhas"},
{id: 192, name: "Caniçal"},
{id: 193, name: "Caniço"},
{id: 194, name: "Canidelo"},
{id: 195, name: "Cantanhede"},
{id: 196, name: "Caparica"},
{id: 197, name: "Caranguejeira"},
{id: 198, name: "Carapinheira"},
{id: 199, name: "Carapito"},
{id: 200, name: "Carcavelos"},
{id: 201, name: "Carnaxide"},
{id: 202, name: "Carragosa"},
{id: 203, name: "Carrapateira"},
{id: 204, name: "Carrazeda de Anciães"},
{id: 205, name: "Carregado"},
{id: 206, name: "Carregal do Sal"},
{id: 207, name: "Cartaxo"},
{id: 208, name: "Carvalhosa"},
{id: 209, name: "Carvoeiro"},
{id: 210, name: "Casais Robustos"},
{id: 211, name: "Cascais"},
{id: 212, name: "Castanheira de Pêra"},
{id: 213, name: "Castanheira do Ribatejo"},
{id: 214, name: "Castelo Branco"},
{id: 215, name: "Castelo de Vide"},
{id: 216, name: "Castelões de Cepeda"},
{id: 217, name: "Castro Daire"},
{id: 218, name: "Castro de Avelãs"},
{id: 219, name: "Castro Marim"},
{id: 220, name: "Castro Verde"},
{id: 221, name: "Caxias"},
{id: 222, name: "Cedros"},
{id: 223, name: "Cela"},
{id: 224, name: "Cercal"},
{id: 225, name: "Charneca de Caparica"},
{id: 226, name: "Charneca"},
{id: 227, name: "Chavão"},
{id: 228, name: "Chaves"},
{id: 229, name: "Coimbra"},
{id: 230, name: "Colares"},
{id: 231, name: "Comenda"},
{id: 232, name: "Comporta"},
{id: 233, name: "Conceição"},
{id: 234, name: "Condeixa-a-Nova"},
{id: 235, name: "Constância"},
{id: 236, name: "Corroios"},
{id: 237, name: "Cortegaça"},
{id: 238, name: "Cortiçada"},
{id: 239, name: "Coruche"},
{id: 240, name: "Costa de Caparica"},
{id: 241, name: "Covilhã"},
{id: 242, name: "Cristelo"},
{id: 243, name: "Cuba"},
{id: 244, name: "Cucujães"},
{id: 245, name: "Curral das Freiras"},
{id: 246, name: "Custoias"},
{id: 247, name: "Darque"},
{id: 248, name: "Donai"},
{id: 249, name: "Eirado"},
{id: 250, name: "Eixo"},
{id: 251, name: "Elvas"},
{id: 252, name: "Entroncamento"},
{id: 253, name: "Ericeira"},
{id: 254, name: "Ermesinde"},
{id: 255, name: "Ervedosa do Douro"},
{id: 256, name: "Esgueira"},
{id: 257, name: "Esmoriz"},
{id: 258, name: "Espargo"},
{id: 259, name: "Espiche"},
{id: 260, name: "Espinho"},
{id: 261, name: "Esporões"},
{id: 262, name: "Esposende"},
{id: 263, name: "Estela"},
{id: 264, name: "Estói"},
{id: 265, name: "Estômbar"},
{id: 266, name: "Estoril"},
{id: 267, name: "Estreito da Calheta"},
{id: 268, name: "Estremoz"},
{id: 269, name: "Évora"},
{id: 270, name: "Fafe"},
{id: 271, name: "Faial"},
{id: 272, name: "Fajã da Ovelha"},
{id: 273, name: "Fajã de Baixo"},
{id: 274, name: "Fajã Grande"},
{id: 275, name: "Famalicão"},
{id: 276, name: "Famões"},
{id: 277, name: "Fânzeres"},
{id: 278, name: "Faria"},
{id: 279, name: "Faro do Alentejo"},
{id: 280, name: "Faro"},
{id: 281, name: "Fátima"},
{id: 282, name: "Favaios"},
{id: 283, name: "Fazenda de Santa Cruz"},
{id: 284, name: "Fazendas de Almeirim"},
{id: 285, name: "Feira"},
{id: 286, name: "Felgueiras"},
{id: 287, name: "Fenais da Ajuda"},
{id: 288, name: "Fenais da Luz"},
{id: 289, name: "Ferragudo"},
{id: 290, name: "Ferreira do Alentejo"},
{id: 291, name: "Ferreira"},
{id: 292, name: "Ferreiras"},
{id: 293, name: "Ferreiros"},
{id: 294, name: "Ferrel"},
{id: 295, name: "Feteira"},
{id: 296, name: "Fiães"},
{id: 297, name: "Figueira da Foz"},
{id: 298, name: "Figueira do Guincho"},
{id: 299, name: "Figueiró"},
{id: 300, name: "Fontanelas"},
{id: 301, name: "Fonte Bastardo"},
{id: 302, name: "Fontelo"},
{id: 303, name: "Fontes"},
{id: 304, name: "Fornelos"},
{id: 305, name: "Foz do Arelho"},
{id: 306, name: "Foz do Douro"},
{id: 307, name: "Foz do Sousa"},
{id: 308, name: "Fradelos"},
{id: 309, name: "Frazão"},
{id: 310, name: "Freamunde"},
{id: 311, name: "Freixo de Espada à Cinta"},
{id: 312, name: "Freixo de Numão"},
{id: 313, name: "Friumes"},
{id: 314, name: "Frossos"},
{id: 315, name: "Funchal"},
{id: 316, name: "Fundão"},
{id: 317, name: "Furnas"},
{id: 318, name: "Fuzeta"},
{id: 319, name: "Gafanha da Encarnação"},
{id: 320, name: "Gafanha da Nazaré"},
{id: 321, name: "Gáfete"},
{id: 322, name: "Galegos"},
{id: 323, name: "Gandra"},
{id: 324, name: "Gavião"},
{id: 325, name: "Gemunde"},
{id: 326, name: "Gimonde"},
{id: 327, name: "Goães"},
{id: 328, name: "Godim"},
{id: 329, name: "Góis"},
{id: 330, name: "Golegã"},
{id: 331, name: "Gondizalves"},
{id: 332, name: "Gondomar"},
{id: 333, name: "Gostei"},
{id: 334, name: "Gradiz"},
{id: 335, name: "Grândola"},
{id: 336, name: "Grijó"},
{id: 337, name: "Guarda"},
{id: 338, name: "Gueral"},
{id: 339, name: "Guia"},
{id: 340, name: "Guifões"},
{id: 341, name: "Guimarães"},
{id: 342, name: "Guisande"},
{id: 343, name: "Gulpilhares"},
{id: 344, name: "Horta"},
{id: 345, name: "Ílhavo"},
{id: 346, name: "Jardim do Mar"},
{id: 347, name: "Joane"},
{id: 348, name: "Jovim"},
{id: 349, name: "Lago"},
{id: 350, name: "Lagoa"},
{id: 351, name: "Lagoaça"},
{id: 352, name: "Lagos"},
{id: 353, name: "Lajes das Flores"},
{id: 354, name: "Lajes"},
{id: 355, name: "Lalim"},
{id: 356, name: "Lamas"},
{id: 357, name: "Lamego"},
{id: 358, name: "Lamelas"},
{id: 359, name: "Lapa do Lobo"},
{id: 360, name: "Laranjeira"},
{id: 361, name: "Laranjeiro"},
{id: 362, name: "Lavos"},
{id: 363, name: "Lavra"},
{id: 364, name: "Lavradio"},
{id: 365, name: "Leça da Palmeira"},
{id: 366, name: "Leça do Bailio"},
{id: 367, name: "Leiria"},
{id: 368, name: "Linda-a-Velha"},
{id: 369, name: "Lisbon"},
{id: 370, name: "Lobão"},
{id: 371, name: "Lomba"},
{id: 372, name: "Lordelo"},
{id: 373, name: "Loriga"},
{id: 374, name: "Lorvão"},
{id: 375, name: "Loulé"},
{id: 376, name: "Loures"},
{id: 377, name: "Louriçal"},
{id: 378, name: "Lourinhã"},
{id: 379, name: "Lourosa"},
{id: 380, name: "Lousã"},
{id: 381, name: "Lousada"},
{id: 382, name: "Lugar de Baixo"},
{id: 383, name: "Luso"},
{id: 384, name: "Lustosa"},
{id: 385, name: "Luz"},
{id: 386, name: "Macedo de Cavaleiros"},
{id: 387, name: "Maceira"},
{id: 388, name: "Machico"},
{id: 389, name: "Macieira de Cambra"},
{id: 390, name: "Macieira de Rates"},
{id: 391, name: "Madalena do Mar"},
{id: 392, name: "Madalena"},
{id: 393, name: "Mafra"},
{id: 394, name: "Maia"},
{id: 395, name: "Malveira"},
{id: 396, name: "Manadas"},
{id: 397, name: "Mangualde"},
{id: 398, name: "Manta Rota"},
{id: 399, name: "Manteigas"},
{id: 400, name: "Marco de Canavezes"},
{id: 401, name: "Margaride"},
{id: 402, name: "Marinha Grande"},
{id: 403, name: "Marinhais"},
{id: 404, name: "Marinhas"},
{id: 405, name: "Mariz"},
{id: 406, name: "Marmelete"},
{id: 407, name: "Martinchel"},
{id: 408, name: "Marvão"},
{id: 409, name: "Massamá"},
{id: 410, name: "Matosinhos"},
{id: 411, name: "Meadela"},
{id: 412, name: "Mealhada"},
{id: 413, name: "Meca"},
{id: 414, name: "Mêda"},
{id: 415, name: "Meinedo"},
{id: 416, name: "Meixedo"},
{id: 417, name: "Melres"},
{id: 418, name: "Mem Martins"},
{id: 419, name: "Merelim"},
{id: 420, name: "Mértola"},
{id: 421, name: "Mesão Frio"},
{id: 422, name: "Mesquitela"},
{id: 423, name: "Mexilhoeira Grande"},
{id: 424, name: "Milhão"},
{id: 425, name: "Milharado"},
{id: 426, name: "Milheirós de Poiares"},
{id: 427, name: "Milheirós"},
{id: 428, name: "Minas de São Domingos"},
{id: 429, name: "Minde"},
{id: 430, name: "Mindelo"},
{id: 431, name: "Mira"},
{id: 432, name: "Miranda do Corvo"},
{id: 433, name: "Miranda do Douro"},
{id: 434, name: "Mirandela"},
{id: 435, name: "Mogadouro"},
{id: 436, name: "Moimenta da Beira"},
{id: 437, name: "Moita dos Ferreiros"},
{id: 438, name: "Moita"},
{id: 439, name: "Moitas Venda"},
{id: 440, name: "Mombeja"},
{id: 441, name: "Monção"},
{id: 442, name: "Moncarapacho"},
{id: 443, name: "Monchique"},
{id: 444, name: "Mondim da Beira"},
{id: 445, name: "Mondim de Basto"},
{id: 446, name: "Monforte"},
{id: 447, name: "Monsanto"},
{id: 448, name: "Montalvinho"},
{id: 449, name: "Montalvo"},
{id: 450, name: "Montargil"},
{id: 451, name: "Monte Estoril"},
{id: 452, name: "Monte Gordo"},
{id: 453, name: "Monte Real"},
{id: 454, name: "Monte Redondo"},
{id: 455, name: "Montemor-o-Novo"},
{id: 456, name: "Montemor-o-Velho"},
{id: 457, name: "Montijo"},
{id: 458, name: "Moreira de Conegos"},
{id: 459, name: "Moreira"},
{id: 460, name: "Moscavide e Portela"},
{id: 461, name: "Mosteirô"},
{id: 462, name: "Mosteiros"},
{id: 463, name: "Moura"},
{id: 464, name: "Mozelos"},
{id: 465, name: "Murtosa"},
{id: 466, name: "Nadadouro"},
{id: 467, name: "Nazaré"},
{id: 468, name: "Negreiros"},
{id: 469, name: "Negrelos"},
{id: 470, name: "Nelas"},
{id: 471, name: "Neves"},
{id: 472, name: "Nisa"},
{id: 473, name: "Nogueira da Regedoura"},
{id: 474, name: "Nogueira"},
{id: 475, name: "Norte Pequeno"},
{id: 476, name: "Nossa Senhora do Monte"},
{id: 477, name: "Óbidos"},
{id: 478, name: "Odeceixe"},
{id: 479, name: "Odemira"},
{id: 480, name: "Odivelas"},
{id: 481, name: "Oeiras"},
{id: 482, name: "Oiã"},
{id: 483, name: "Oleiros"},
{id: 484, name: "Olhão"},
{id: 485, name: "Olhos de Água"},
{id: 486, name: "Olivais"},
{id: 487, name: "Olival do Basto"},
{id: 488, name: "Olival"},
{id: 489, name: "Oliveira de Azemeis"},
{id: 490, name: "Oliveira do Bairro"},
{id: 491, name: "Oliveira do Douro"},
{id: 492, name: "Oliveira do Hospital"},
{id: 493, name: "Oliveira do Mondego"},
{id: 494, name: "Oliveira"},
{id: 495, name: "Oliveirinha"},
{id: 496, name: "Ota"},
{id: 497, name: "Ourém"},
{id: 498, name: "Ovar"},
{id: 499, name: "Paço de Arcos"},
{id: 500, name: "Paços de Brandão"},
{id: 501, name: "Paços de Ferreira"},
{id: 502, name: "Paderne"},
{id: 503, name: "Paialvo"},
{id: 504, name: "Palmela"},
{id: 505, name: "Pampilhosa da Serra"},
{id: 506, name: "Pampilhosa do Botão"},
{id: 507, name: "Parada de Gonta"},
{id: 508, name: "Paradela"},
{id: 509, name: "Parchal"},
{id: 510, name: "Pardilhó"},
{id: 511, name: "Parede"},
{id: 512, name: "Paredes"},
{id: 513, name: "Pataias"},
{id: 514, name: "Paul do Mar"},
{id: 515, name: "Pedrógão Grande"},
{id: 516, name: "Pedroso"},
{id: 517, name: "Pedrouços"},
{id: 518, name: "Pego"},
{id: 519, name: "Penacova"},
{id: 520, name: "Penafiel"},
{id: 521, name: "Penedo Gordo"},
{id: 522, name: "Penedono"},
{id: 523, name: "Peniche"},
{id: 524, name: "Pêra Velha"},
{id: 525, name: "Pêra"},
{id: 526, name: "Perafita"},
{id: 527, name: "Pereiro da Palhacana"},
{id: 528, name: "Perelhal"},
{id: 529, name: "Pero Pinheiro"},
{id: 530, name: "Peroguarda"},
{id: 531, name: "Perozinho"},
{id: 532, name: "Peso da Régua"},
{id: 533, name: "Piedade"},
{id: 534, name: "Pinhal Novo"},
{id: 535, name: "Pinhão"},
{id: 536, name: "Pinheiro Grande"},
{id: 537, name: "Pinheiro"},
{id: 538, name: "Poceirão"},
{id: 539, name: "Poço do Canto"},
{id: 540, name: "Podence"},
{id: 541, name: "Poiares"},
{id: 542, name: "Pombal"},
{id: 543, name: "Pombalinho"},
{id: 544, name: "Ponta Delgada"},
{id: 545, name: "Ponta do Pargo"},
{id: 546, name: "Ponta do Sol"},
{id: 547, name: "Ponta Garça"},
{id: 548, name: "Ponte da Barca"},
{id: 549, name: "Ponte de Lima"},
{id: 550, name: "Ponte de Sôr"},
{id: 551, name: "Ponte"},
{id: 552, name: "Pontével"},
{id: 553, name: "Pontinha"},
{id: 554, name: "Porches"},
{id: 555, name: "Portalegre"},
{id: 556, name: "Portimão"},
{id: 557, name: "Porto Covo"},
{id: 558, name: "Porto da Cruz"},
{id: 559, name: "Porto de Mós"},
{id: 560, name: "Porto Judeu"},
{id: 561, name: "Porto Martins"},
{id: 562, name: "Porto Moniz"},
{id: 563, name: "Porto Salvo"},
{id: 564, name: "Porto"},
{id: 565, name: "Póvoa da Raposeira"},
{id: 566, name: "Póvoa de Lanhoso"},
{id: 567, name: "Póvoa de Santa Iria"},
{id: 568, name: "Póvoa de Santo Adrião"},
{id: 569, name: "Póvoa de Varzim"},
{id: 570, name: "Povoação"},
{id: 571, name: "Prado"},
{id: 572, name: "Pragal"},
{id: 573, name: "Praia da Graciosa"},
{id: 574, name: "Praia da Vitória"},
{id: 575, name: "Praia do Ribatejo"},
{id: 576, name: "Prazeres"},
{id: 577, name: "Prior Velho"},
{id: 578, name: "Proença-a-Nova"},
{id: 579, name: "Quarteira"},
{id: 580, name: "Queijas"},
{id: 581, name: "Queluz"},
{id: 582, name: "Quinta do Anjo"},
{id: 583, name: "Quinta Do Conde"},
{id: 584, name: "Quintanilha"},
{id: 585, name: "Quintela"},
{id: 586, name: "Rabal"},
{id: 587, name: "Rabo de Peixe"},
{id: 588, name: "Ramada"},
{id: 589, name: "Real"},
{id: 590, name: "Rebordões"},
{id: 591, name: "Rebordosa"},
{id: 592, name: "Recarei"},
{id: 593, name: "Redondo"},
{id: 594, name: "Refojos de Basto"},
{id: 595, name: "Reguengos de Monsaraz"},
{id: 596, name: "Relva"},
{id: 597, name: "Rendufe"},
{id: 598, name: "Resende"},
{id: 599, name: "Riachos"},
{id: 600, name: "Riba de Ave"},
{id: 601, name: "Ribeira Brava"},
{id: 602, name: "Ribeira Chã"},
{id: 603, name: "Ribeira das Tainhas"},
{id: 604, name: "Ribeira Grande"},
{id: 605, name: "Ribeira Quente"},
{id: 606, name: "Ribeira Seca"},
{id: 607, name: "Ribeirão"},
{id: 608, name: "Ribeirinha"},
{id: 609, name: "Rio de Loba"},
{id: 610, name: "Rio de Mouro"},
{id: 611, name: "Rio Maior"},
{id: 612, name: "Rio Mau"},
{id: 613, name: "Rio Meão"},
{id: 614, name: "Rio Tinto"},
{id: 615, name: "Rochoso"},
{id: 616, name: "Ronfe"},
{id: 617, name: "Rosairinho"},
{id: 618, name: "Rosais"},
{id: 619, name: "Rosto de Cão"},
{id: 620, name: "Rua"},
{id: 621, name: "Rubiãis"},
{id: 622, name: "Sabrosa"},
{id: 623, name: "Sacavém"},
{id: 624, name: "Sagres"},
{id: 625, name: "Salir de Matos"},
{id: 626, name: "Salir do Porto"},
{id: 627, name: "Salreu"},
{id: 628, name: "Salvada"},
{id: 629, name: "Salvaterra de Magos"},
{id: 630, name: "Samil"},
{id: 631, name: "Samora Correia"},
{id: 632, name: "Samouco"},
{id: 633, name: "Sande"},
{id: 634, name: "Sandim"},
{id: 635, name: "Sanfins"},
{id: 636, name: "Sangalhos"},
{id: 637, name: "Santa Bárbara de Nexe"},
{id: 638, name: "Santa Bárbara"},
{id: 639, name: "Santa Catarina da Serra"},
{id: 640, name: "Santa Clara de Louredo"},
{id: 641, name: "Santa Clara"},
{id: 642, name: "Santa Comba Dão"},
{id: 643, name: "Santa Cruz da Graciosa"},
{id: 644, name: "Santa Cruz das Flores"},
{id: 645, name: "Santa Cruz do Bispo"},
{id: 646, name: "Santa Cruz"},
{id: 647, name: "Santa Iria da Azóia"},
{id: 648, name: "Santa Luzia"},
{id: 649, name: "Santa Margarida da Coutada"},
{id: 650, name: "Santa Ovaia"},
{id: 651, name: "Santa Vitória"},
{id: 652, name: "Santana"},
{id: 653, name: "Santarém"},
{id: 654, name: "Santiago do Cacém"},
{id: 655, name: "Santo André"},
{id: 656, name: "Santo Antão do Tojal"},
{id: 657, name: "Santo Antão"},
{id: 658, name: "Santo António da Charneca"},
{id: 659, name: "Santo António dos Olivais"},
{id: 660, name: "Santo da Serra"},
{id: 661, name: "Santo Isidoro"},
{id: 662, name: "Santo Izidoro"},
{id: 663, name: "Santo Tirso"},
{id: 664, name: "Santos-o-Velho"},
{id: 665, name: "São Bartolomeu de Messines"},
{id: 666, name: "São Bartolomeu"},
{id: 667, name: "São Brás de Alportel"},
{id: 668, name: "São Brissos"},
{id: 669, name: "São Domingos de Rana"},
{id: 670, name: "São Félix da Marinha"},
{id: 671, name: "São Jacinto"},
{id: 672, name: "São João da Madeira"},
{id: 673, name: "São João da Pesqueira"},
{id: 674, name: "São João da Talha"},
{id: 675, name: "São João das Lampas"},
{id: 676, name: "São João de Areias"},
{id: 677, name: "São João de Ver"},
{id: 678, name: "São João dos Montes"},
{id: 679, name: "São João"},
{id: 680, name: "São Jorge da Beira"},
{id: 681, name: "São Jorge"},
{id: 682, name: "São Luis"},
{id: 683, name: "São Mamede de Infesta"},
{id: 684, name: "São Marcos da Serra"},
{id: 685, name: "São Martinho do Porto"},
{id: 686, name: "São Martinho"},
{id: 687, name: "São Mateus"},
{id: 688, name: "São Matias"},
{id: 689, name: "São Miguel de Rio Torto"},
{id: 690, name: "São Miguel do Couto"},
{id: 691, name: "São Pedro da Cadeira"},
{id: 692, name: "São Pedro da Cova"},
{id: 693, name: "São Pedro de Alva"},
{id: 694, name: "São Pedro de Serracenos"},
{id: 695, name: "São Pedro do Sul"},
{id: 696, name: "São Romão do Coronado"},
{id: 697, name: "São Romão"},
{id: 698, name: "São Roque do Pico"},
{id: 699, name: "São Roque"},
{id: 700, name: "São Sebastião"},
{id: 701, name: "São Simão / Pé da Serra"},
{id: 702, name: "São Teotónio"},
{id: 703, name: "São Vicente do Paul"},
{id: 704, name: "São Vicente"},
{id: 705, name: "Sardoal"},
{id: 706, name: "Sarilhos Pequenos"},
{id: 707, name: "Sátão"},
{id: 708, name: "Sazes da Beira"},
{id: 709, name: "Seia"},
{id: 710, name: "Seixal"},
{id: 711, name: "Selho"},
{id: 712, name: "Semelhe"},
{id: 713, name: "Sendim"},
{id: 714, name: "Senhora da Hora"},
{id: 715, name: "Senhora da Luz"},
{id: 716, name: "Senhora do Rosário"},
{id: 717, name: "Sequeira"},
{id: 718, name: "Sequeiros"},
{id: 719, name: "Sermonde"},
{id: 720, name: "Sernancelhe"},
{id: 721, name: "Seroa"},
{id: 722, name: "Serpa"},
{id: 723, name: "Serra de El-Rei"},
{id: 724, name: "Serra do Bouro"},
{id: 725, name: "Sertã"},
{id: 726, name: "Serzedelo"},
{id: 727, name: "Serzedo"},
{id: 728, name: "Sesimbra"},
{id: 729, name: "Sete Cidades"},
{id: 730, name: "Setúbal"},
{id: 731, name: "Silvalde"},
{id: 732, name: "Silveira"},
{id: 733, name: "Silves"},
{id: 734, name: "Sines"},
{id: 735, name: "Sintra"},
{id: 736, name: "Sobrado"},
{id: 737, name: "Sobral de Monte Agraço"},
{id: 738, name: "Sobralinho"},
{id: 739, name: "Sobreda"},
{id: 740, name: "Sobreira"},
{id: 741, name: "Soure"},
{id: 742, name: "Souto da Carpalhosa"},
{id: 743, name: "Souto de Aguiar"},
{id: 744, name: "Souto"},
{id: 745, name: "Tábua"},
{id: 746, name: "Tabuaço"},
{id: 747, name: "Tamera"},
{id: 748, name: "Tancos"},
{id: 749, name: "Tarouca"},
{id: 750, name: "Tavarede"},
{id: 751, name: "Tavira"},
{id: 752, name: "Tebosa"},
{id: 753, name: "Teixoso"},
{id: 754, name: "Telões"},
{id: 755, name: "Terrugem"},
{id: 756, name: "Tocha"},
{id: 757, name: "Tomar"},
{id: 758, name: "Tondela"},
{id: 759, name: "Torre de Moncorvo"},
{id: 760, name: "Torres Novas"},
{id: 761, name: "Torres Vedras"},
{id: 762, name: "Trafaria"},
{id: 763, name: "Tramagal"},
{id: 764, name: "Travanca"},
{id: 765, name: "Treixedo"},
{id: 766, name: "Trevões"},
{id: 767, name: "Trigaches"},
{id: 768, name: "Trofa"},
{id: 769, name: "Tunes"},
{id: 770, name: "Turquel"},
{id: 771, name: "Unhais-o-Velho"},
{id: 772, name: "Unhos"},
{id: 773, name: "Urgeses"},
{id: 774, name: "Urzelina"},
{id: 775, name: "Vagos"},
{id: 776, name: "Vairão"},
{id: 777, name: "Valadares"},
{id: 778, name: "Valado de Frades"},
{id: 779, name: "Valbom"},
{id: 780, name: "Vale da Amoreira"},
{id: 781, name: "Vale de Cambra"},
{id: 782, name: "Vale de Figueira"},
{id: 783, name: "Vale de Santarém"},
{id: 784, name: "Válega"},
{id: 785, name: "Valenza"},
{id: 786, name: "Vales do Rio"},
{id: 787, name: "Valongo"},
{id: 788, name: "Valpaços"},
{id: 789, name: "Valverde"},
{id: 790, name: "Várzea"},
{id: 791, name: "Velas"},
{id: 792, name: "Venda do Pinheiro"},
{id: 793, name: "Vendas Novas"},
{id: 794, name: "Ventosa"},
{id: 795, name: "Vestiaria"},
{id: 796, name: "Vialonga"},
{id: 797, name: "Viana do Castelo"},
{id: 798, name: "Vidais"},
{id: 799, name: "Vide"},
{id: 800, name: "Vidigueira"},
{id: 801, name: "Vieira de Leiria"},
{id: 802, name: "Vieira do Minho"},
{id: 803, name: "Vila Chã de Ourique"},
{id: 804, name: "Vila Chã"},
{id: 805, name: "Vila Cova"},
{id: 806, name: "Vila de Rei"},
{id: 807, name: "Vila do Bispo"},
{id: 808, name: "Vila do Conde"},
{id: 809, name: "Vila do Corvo"},
{id: 810, name: "Vila do Porto"},
{id: 811, name: "Vila Franca de Xira"},
{id: 812, name: "Vila Franca do Campo"},
{id: 813, name: "Vila Frescainha"},
{id: 814, name: "Vila Meã"},
{id: 815, name: "Vila Nova da Barquinha"},
{id: 816, name: "Vila Nova da Telha"},
{id: 817, name: "Vila Nova De Cacela"},
{id: 818, name: "Vila Nova de Ceira"},
{id: 819, name: "Vila Nova de Famalicão"},
{id: 820, name: "Vila Nova de Foz Côa"},
{id: 821, name: "Vila Nova de Gaia"},
{id: 822, name: "Vila Nova de Milfontes"},
{id: 823, name: "Vila Nova de Paiva"},
{id: 824, name: "Vila Praia de Âncora"},
{id: 825, name: "Vila Real de Santo António"},
{id: 826, name: "Vila Real"},
{id: 827, name: "Vila Seca"},
{id: 828, name: "Vila Velha de Ródão"},
{id: 829, name: "Vila Verde"},
{id: 830, name: "Vila Viçosa"},
{id: 831, name: "Vilaça"},
{id: 832, name: "Vilamoura"},
{id: 833, name: "Vilar de Andorinho"},
{id: 834, name: "Vilar de Figos"},
{id: 835, name: "Vilar do Paraíso"},
{id: 836, name: "Vilarinho"},
{id: 837, name: "Vilela"},
{id: 838, name: "Vimeiro"},
{id: 839, name: "Vinhais"},
{id: 840, name: "Viseu"},
{id: 841, name: "Vizela"},
{id: 842, name: "Zambujeira do Mar"}
